### ISSUE TITLE
crypto.getRandomValues is not supported uuidv4

### ISSUE THREAD

**Issue by lucasile** [Minjun1Kim/ReactNativeAppDemo#1]
crypto.getRandomValues is not supported uuidv4

In the case that this issues comes up, a way to fix it is to polyfill with ['react-native-get-random-values'](https://www.npmjs.com/package/react-native-get-random-values)

Import before uuid import.

```JS
import 'react-native-get-random-values'
import { v4 as uuidv4 } from 'uuid';
```

**Comment by Minjun1Kim** [comment]
Thank you for the suggestion.
Alternatively, you can also run the following command in the terminal:

```shell
npm install uuid
```

**Comment by lucasile** [comment]
> Thank you for the suggestion. Alternatively, you can also run the following command in the terminal:
> 
> ```shell
> npm install uuid
> ```

This is not an issue regarding uuid being not installed.

I'm not sure why this occurs, but see this stackoverflow thread. It most likely won't happen, but it happened for me.
https://stackoverflow.com/questions/61169746/crypto-getrandomvalues-not-supported

**Comment by Minjun1Kim** [comment]
I see, thank you!
This seems like an Android problem.

I will add these to the README.
